# coding:utf-8

# DO NOT EDIT THIS FILE MANUALLY.
# This file is automatically generated by the installer release script (release.sh).

# This is the version of the scalr-manage CLI
__version__ = "7.12.0"

# This is the corresponding version of the installer-ng cookbooks.
__pkg_version__ = "7.12.0"

