#!/bin/bash
#
# Perform necessary test setup steps
# after package is installed.
#
# Adapted from: https://github.com/chef/omnibus-chef/blob/master/package-scripts/chef/postinst

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

binaries="ctl manage wizard"
for binary in ${binaries}; do
  ln -sf "/opt/scalr-server/bin/scalr-server-${binary}" "/usr/bin" || error_exit "Cannot link scalr-server-${binary} in /usr/bin"
done

echo -e "\033[1mThank you for installing Scalr!\033[0m"
echo
echo "The next step in the install process is to run:"
echo
echo -e "\033[1msudo scalr-server-wizard\033[0m"

exit 0
