#!/bin/sh

set -o errexit

conf="/opt/scalr-server/etc/supervisor/supervisord.conf"

if [ ! -f "$conf" ]; then
    echo "Not available yet!"
    echo "You must run 'scalr-server-ctl reconfigure' first."
    exit 1
fi

if [ "x$1" = "xrestart" ] && [ "x$2" = "xall" ]; then
    for service in $(scalr-server-manage status|awk '{print $1}'); do
        scalr-server-manage restart "${service}"
    done
elif [ "x$1" = "xrestart" ]; then
    scalr-server-manage stop "$2"
    scalr-server-manage start "$2"
elif [ "x$1" = "xstop" ]; then
    echo -n "Stop $2 service(s) ... "

    /opt/scalr-server/embedded/bin/supervisorctl \
    -c "$conf" \
    "stop $2" > /dev/null

    echo "[ \033[32mOK\033[0m ]"

elif [ "x$1" = "xstart" ]; then
    echo -n "Start $2 service(s) ... "

    /opt/scalr-server/embedded/bin/supervisorctl \
    -c "$conf" \
    "start $2" > /dev/null

    echo "[ \033[32mOK\033[0m ]"
elif [ "x$1" = "xsync-shared-roles" ]; then
    echo "Syncing shared roles ... "
    /opt/scalr-server/embedded/bin/php /opt/scalr-server/embedded/scalr/app/tools/sync_shared_roles.php
    echo ""
else
    /opt/scalr-server/embedded/bin/supervisorctl \
    -c "$conf" \
    "$@"
fi

